services:
  app:
    build: .
    container_name: async-csv-import-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - /var/www/html/projetos/async-csv-import:/var/www/html
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    container_name: async-csv-import-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: csv-import-app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123*321
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: async-csv-import-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  queue:
    build: .
    container_name: async-csv-import-queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work
    depends_on:
      - redis
      - app
    volumes:
      - /var/www/html/projetos/async-csv-import:/var/www/html

volumes:
  dbdata:
